image: python:3.12.6

before_script:
  - apt-get update && apt-get install -y libgl1-mesa-glx

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pytest
  only:
    - merge_requests
    - main
