game:
  honesties: [0.2, 0.8, 1]
  n_agents: 3 # Number of agents in simulation
  n_rounds: 50 # Number of conversation rounds
  n_stat: 2 # Number of simulations for statistic batch (different seeds)
  characters_dict: [{"all": "ordinary"}, {0: "deceptive"}] # Characters of each agent
  folder: "evaluate/results" # Result folder
  mindI: []
  Ks: []

randomseed:
  seed: 21 # 21 is a nice simulation
  seed_offset: 0

multiprocessing:
  n_parallel_core_jobs: 2

parameters:
  p_one_to_one: 1 # which fraction of conversations is 1-to-1

constants:
  TINY: 0.001
  MIN_KL: -0.9999
  MAX_COUNT: 1000000 # maximal number of counts allowed to be memorized
  agent_color: ["red", "black", "cyan", "yellow", "blue", "grey", "green"] # colors for the agents; if too small, list is repeated
  agent_color_alpha: [1, 0.85, 1.5, 1.5, 1, 1, 0.85] # transparency values for plotting, adjusted to Acolor; if too small, list is repeated
  BLUSH_FREQ_LIE: 0.1

switches:
  COMPRESSION_METHOD: "KL_minimization" # choose between 'KL_minimization', 'moment_matching', 'LUT'
  OPTIMIZATION_METHOD: "trust-constr" # choose between 'trust-costr', 'L-BFGS-B'
  GTOL: 0.001
  
  RANDOM_HONESTIES: True # if True, intrinsic honesties of agents will be randomly distributed. If False, thay are equally distributed between 0 and 1. make shure honesties is None in the game specification
  ACTIVE_SELF_FRIENDSHIP: False # if True, agents can become enemies of theirown. Else, they always regard themselves as friends
  SCALED_FLATTERING: False # if True, flattering is scaled with perceived dishonesty of the receiver. If False: flattered lies are always maximally positive
  FRIENDSHIP_AFFECTS_B: False # if True, ordinary agents' selection of communication partners will be affected by friendships
  FRIENDSHIP_AFFECTS_C: False # if True, ordinary agents' selection of communication topics will be affected by friendships
  RELATION_AFFECTS_B: False # if True, ordinary agents' selection of communication partners will be affected by their relation strength
  RELATION_AFFECTS_C: False # if True, ordinary agents' selection of communication topics will be affected by their relation strength
  RANDOM_FRIENDSHIP_AFFINITIES: False # if True, intrinsic friendship affinities will be drawn randomly. If False, they are all 1

names_dict: {
    "deaf": "00_deaf",
    "naive": "01_naive",
    "uncritical": "03_uncritical",
    "ordinary": "04_ordinary",
    "strategic": "05_strategic",
    "egocentric": "06_egocentric",
    "deceptive": "07_deceptive",
    "flattering": "08_flattering",
    "aggressive": "09_aggressive",
    "shameless": "10_shameless",
    "smart": "11_smart",
    "clever": "12_clever",
    "manipulative": "13_manipulative",
    "dominant": "14_dominant",
    "destructive": "15_destructive",
    "good": "16_good",
    "antistrategic": "17_antistrategic",
}